const express=require('express'),multer=require('multer'),{v2:cloudinary}=require('cloudinary'),{pool}=require('../db');
const router=express.Router();const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024},fileFilter:(r,f,cb)=>cb(null,['image/jpeg','image/png','image/webp','image/gif'].includes(f.mimetype))});
cloudinary.config({cloud_name:process.env.CLOUDINARY_CLOUD_NAME,api_key:process.env.CLOUDINARY_API_KEY,api_secret:process.env.CLOUDINARY_API_SECRET});
function image(f){return new Promise((ok,no)=>{let s=cloudinary.uploader.upload_stream({folder:'nobody/posts'},(e,r)=>e?no(e):ok(r.secure_url));s.end(f.buffer)})}
function clean(p,cs=[]){return{id:p.id,name:p.name,age:p.age,joined:p.joined,category:p.category,mood:p.mood,type:p.type,pref:p.pref,body:p.body,imageUrl:p.image_url,reactions:p.reactions,comments:cs,createdAt:new Date(p.created_at).getTime()}}
router.get('/',async(req,res)=>{try{let ps=(await pool.query('SELECT * FROM posts ORDER BY created_at DESC')).rows,ids=ps.map(p=>p.id),cs=ids.length?(await pool.query('SELECT * FROM comments WHERE post_id=ANY($1::int[]) ORDER BY created_at',[ids])).rows:[];res.json(ps.map(p=>clean(p,cs.filter(c=>c.post_id===p.id).map(c=>({id:c.id,name:c.name,text:c.text,createdAt:new Date(c.created_at).getTime()}))))) }catch(e){res.status(500).json({error:'Could not load feed.'})}});
router.post('/',upload.single('image'),async(req,res)=>{try{let{body,category,type,mood,pref}=req.body;if(!body?.trim())return res.status(400).json({error:'Post body is required.'});let url=req.file?await image(req.file):null,u=req.user,ps=(await pool.query(`INSERT INTO posts(owner_id,name,age,joined,category,mood,type,pref,body,image_url) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[u.id,u.profile.name,u.profile.ageRange,u.profile.joined,category||'Just Venting',mood||'😐',type||'Vent',pref||'PUBLIC',body.trim(),url])).rows[0];res.status(201).json(clean(ps))}catch(e){console.error(e);res.status(500).json({error:e.message||'Could not create post.'})}});
router.post('/:id/react',async(req,res)=>{try{let q=await pool.query('SELECT * FROM posts WHERE id=$1',[req.params.id]);if(!q.rowCount)return res.status(404).json({error:'Post not found.'});let r=q.rows[0].reactions||{},t=req.body.type;if(!['Supportive','Helpful','Felt Heard','Good Perspective'].includes(t))return res.status(400).json({error:'Invalid reaction.'});r[t]=(r[t]||0)+1;await pool.query('UPDATE posts SET reactions=$1 WHERE id=$2',[JSON.stringify(r),req.params.id]);res.json({ok:true,reactions:r})}catch(e){res.status(500).json({error:'Could not react.'})}});
router.post('/:id/comments',async(req,res)=>{try{let p=(await pool.query('SELECT * FROM posts WHERE id=$1',[req.params.id])).rows[0];if(!p)return res.status(404).json({error:'Post not found.'});if(p.pref==='PRIVATE')return res.status(403).json({error:'Private responses only.'});let text=String(req.body.text||'').trim();if(!text)return res.status(400).json({error:'Response cannot be empty.'});let c=(await pool.query('INSERT INTO comments(post_id,owner_id,name,text) VALUES($1,$2,$3,$4) RETURNING *',[p.id,req.user.id,req.user.profile.name,text])).rows[0];res.status(201).json({id:c.id,name:c.name,text:c.text,createdAt:new Date(c.created_at).getTime()})}catch(e){res.status(500).json({error:'Could not reply.'})}});
router.delete('/:id',async(req,res)=>{let q=await pool.query('DELETE FROM posts WHERE id=$1 AND owner_id=$2',[req.params.id,req.user.id]);if(!q.rowCount)return res.status(404).json({error:'Post not found.'});res.status(204).end()});
module.exports=router;
